Updated build system for Debian/Ubuntu packages.
git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp-misc/trunk/bibtexconv@1639 acdd8558-d4fd-0310-b0a5-8cf3c1ec824a

diff --git a/build-deb b/build-deb
--- a/build-deb
+++ b/build-deb
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -e
 # $Id$
 #
 # Debian Packaging Scripts
@@ -24,22 +24,65 @@
 
 CHANGELOG_HEADER="`head -n1 debian/changelog`"
 
+# The package name, e.g. MyApplication
 PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`
-PACKAGE_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/[a-Z0-9 ]*(//" -e "s/).*//" -e "s/ //g" -e "s/^[0-9]*://"`
-INPUT_DISTRIBUTION=`echo $CHANGELOG_HEADER | sed -e "s/[^)]*)//" -e "s/;.*//g" -e "s/ //g"`
+# The package distribution, e.g. precise, raring, ...
+PACKAGE_DISTRIBUTION=`echo $CHANGELOG_HEADER | sed -e "s/[^)]*)//" -e "s/;.*//g" -e "s/ //g"`
+# The package's version, e.g. 1.2.3-1ubuntu1
+PACKAGE_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/.*(//" -e "s/).*//" -e "s/ //g" -e "s/ //g"`
 
 
-echo "######################################################################"
-echo "CHANGELOG_HEADER:   $CHANGELOG_HEADER"
-echo "PACKAGE:            $PACKAGE"
-echo "INPUT_DISTRIBUTION: $INPUT_DISTRIBUTION"
-echo "######################################################################"
+echo -e "\x1b[34m######################################################################\x1b[0m"
+echo -e "\x1b[34mCHANGELOG_HEADER:     $CHANGELOG_HEADER\x1b[0m"
+echo -e "\x1b[34mPACKAGE:              $PACKAGE\x1b[0m"
+echo -e "\x1b[34mPACKAGE_DISTRIBUTION: $PACKAGE_DISTRIBUTION\x1b[0m"
+echo -e "\x1b[34mPACKAGE_VERSION       $PACKAGE_VERSION\x1b[0m"
+echo -e "\x1b[34m######################################################################\x1b[0m"
+
+
+echo -e ""
+echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Generating source package ======================================\x1b[0m"
+echo -e ""
 
 sudo echo ""
+./clean-deb
+./make-deb ${PACKAGE_DISTRIBUTION}
 
-./clean-deb && \
-./make-deb ${INPUT_DISTRIBUTION} && \
-DSC_FILE=${PACKAGE}_${PACKAGE_VERSION}~${INPUT_DISTRIBUTION}1~ppa0.dsc && \
-sudo pbuilder build $DSC_FILE && \
-CHANGES_FILE=/var/cache/pbuilder/result/${PACKAGE}_${PACKAGE_VERSION}~${INPUT_DISTRIBUTION}1~ppa0_*.changes && \
-lintian -iIEv --pedantic $CHANGES_FILE
+if [ "$PACKAGE_DISTRIBUTION" = "unstable" -o \
+     "$PACKAGE_DISTRIBUTION" = "testing"  -o \
+     "$PACKAGE_DISTRIBUTION" = "stable"   -o \
+     "$PACKAGE_DISTRIBUTION" = "default" ] ; then
+   if [ "$PACKAGE_DISTRIBUTION" = "default" ] ; then
+      version=${PACKAGE_VERSION}
+   else
+      version=${DEBIAN_VERSION}
+   fi
+   changesFilesPattern="${PACKAGE}_${version}_*.changes"
+   dscFile=`ls ${PACKAGE}_${version}.dsc | tail -n1`
+else
+   changesFilesPattern="${PACKAGE}_${PACKAGE_VERSION}~${PACKAGE_DISTRIBUTION}[0-9]~ppa[0-9]_*.changes"
+   dscFile=`ls ${PACKAGE}_${PACKAGE_VERSION}~${PACKAGE_DISTRIBUTION}[0-9]~ppa[0-9].dsc | tail -n1`
+fi
+
+
+echo -e ""
+echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Building source package ========================================\x1b[0m"
+echo -e ""
+
+if [ ! -e "$dscFile" ] ; then
+    echo >&2 "ERROR: Unable to find description file $dscFile!"
+    exit 1
+fi
+sudo pbuilder build $dscFile
+
+
+echo -e ""
+echo -e "\x1b[34m`date +%FT%H:%M:%S`: ====== Running lintian ================================================\x1b[0m"
+echo -e ""
+
+changesFile=`find /var/cache/pbuilder/result/ -name "${changesFilesPattern}"`
+if [ ! -e "$changesFile" ] ; then
+    echo >&2 "ERROR: Unable to find changes file $changesFile!"
+    exit 1
+fi
+lintian -iIEv --pedantic $changesFilesPattern
