Build script update.
git-svn-id: https://svn.tdr.iem.uni-due.de:8443/svn/sctp-misc/trunk/bibtexconv@1642 acdd8558-d4fd-0310-b0a5-8cf3c1ec824a

diff --git a/build-deb b/build-deb
--- a/build-deb
+++ b/build-deb
@@ -19,7 +19,13 @@
 #
 # Contact: dreibh@iem.uni-due.de
 
+if [ ! -e ./debian.conf ] ; then
+   echo >&2 "ERROR: debian.conf does not exist -> no configuration for the new package!"
+   exit 1
+fi
 . ./debian.conf
+
+OVERRIDE_PACKAGE_DISTRIBUTION="$1"
 
 
 CHANGELOG_HEADER="`head -n1 debian/changelog`"
@@ -50,6 +56,14 @@ echo -e "\x1b[34mDEBIAN_VERSION:       $DEBIAN_VERSION\x1b[0m"
 echo -e "\x1b[34mUPSTREAM_VERSION:     $UPSTREAM_VERSION\x1b[0m"
 echo -e "\x1b[34mPLAIN_VERSION:        $PLAIN_VERSION\x1b[0m"
 echo -e "\x1b[34m######################################################################\x1b[0m"
+
+
+if [ "$OVERRIDE_PACKAGE_DISTRIBUTION" != "" ] ; then
+   PACKAGE_DISTRIBUTION="$OVERRIDE_PACKAGE_DISTRIBUTION"
+   echo ""
+   echo -e "\x1b[34m**** Overriding PACKAGE_DISTRIBUTION: PACKAGE_DISTRIBUTION=${PACKAGE_DISTRIBUTION}! ****\x1b[0m"
+   echo ""
+fi
 
 
 echo -e ""
