Updated examples.

diff --git a/src/run-mypy b/src/run-mypy
--- a/src/run-mypy
+++ b/src/run-mypy
@@ -7,7 +7,7 @@
 #             |____/ \__,_|_|_|\__,_|     |_|\___/ \___/|_|___/
 #
 #                           --- Build-Tools ---
-#                https://www.nntb.no/~dreibh/system-tools/
+#                https://www.nntb.no/~dreibh/build-tools/
 # ==========================================================================
 #
 # Run MyPy for Python Scripts
@@ -35,7 +35,11 @@ set -euo pipefail
 # Automatically find all Python scripts in subdirectories:
 SCRIPTS="$(
 (
-   find . -type f -executable -and -not -name "*~"
+   find . -path '*/.*' -type d -prune \
+      -o \( \
+            \( -type f -perm -100 ! -name "*~" \) \
+            -o -name "*.py" \
+         \) -print
 ) | while read -r name ; do
    if [[ "$(head -n1 "${name}" | strings)" =~ (python) ]] ; then
       echo "${name}"
@@ -111,20 +115,26 @@ if [ ! -x "${MYPY}" ] ; then
 fi
 echo "MyPy: ${MYPY}"
 if ! command -v print-utf8 2>/dev/null ; then
-   echo >&2 "ERROR: Print-UTF8 (from System-Tools) is not installed!"
-   echo >&2 "Try this:"
-   echo >&2 "* Ubuntu:  sudo apt-add-repository -sy ppa:dreibh/ppa"
+   echo >&2 "ERROR: Print-UTF8 (from System-Tools) is not installed! Try:"
+   echo >&2 " * Ubuntu:  sudo apt-add-repository -sy ppa:dreibh/ppa"
    echo >&2 "           sudo apt install -y td-system-tools"
-   echo >&2 "* Fedora:  sudo dnf copr enable -y dreibh/ppa"
+   echo >&2 " * Fedora:  sudo dnf copr enable -y dreibh/ppa"
    echo >&2 "           sudo dnf install -y td-system-tools"
-   echo >&2 "* FreeBSD: sudo pkg install -y td-system-tools"
+   echo >&2 " * FreeBSD: sudo pkg install -y td-system-tools"
+   echo >&2 " * See https://www.nntb.no/~dreibh/system-tools/#binary-package-installation for other systems!"
    exit 1
 fi
-if ! command -v figlet 2>/dev/null ; then
-   echo >&2 "ERROR: Figlet is not installed!"
-   echo >&2 "* Ubuntu:  sudo apt install -y figlet"
-   echo >&2 "* Fedora:  sudo dnf install -y figlet"
-   echo >&2 "* FreeBSD: sudo pkg install -y figlet"
+if ! command -v figlet >/dev/null ; then
+   echo >&2 "ERROR: Figlet is not installed! Try:"
+   echo >&2 " * Ubuntu/Debian: sudo apt install -y figlet"
+   echo >&2 " * Fedora:        sudo dnf install -y figlet"
+   echo >&2 " * OpenSUSE:      sudo zypper install -y figlet"
+   echo >&2 " * Alpine:        sudo apk add figlet"
+   echo >&2 " * FreeBSD:       sudo pkg install -y figlet"
+   echo >&2 " * NetBSD:        sudo pkgin -y install figlet"
+   echo >&2 " * OpenBSD:       sudo pkg_add figlet"
+   echo >&2 " * Solaris:       (install from sources)"
+   echo >&2 " * Apple:         brew install figlet"
    exit 1
 fi
 
