Further improvements.

diff --git a/src/update-ietf-documents b/src/update-ietf-documents
--- a/src/update-ietf-documents
+++ b/src/update-ietf-documents
@@ -23,7 +23,7 @@ REFERENCES=~/src/papers/Referenzarchiv.bib
 DOCUMENTS=`grep -E "^@[a-zA-Z]*{[ \t].*,.*$" "${REFERENCES}" | sed -e "s/,//g" | awk '{ print $2; }' | grep -E "^RFC|^draft"`
 UPDATES_FILE="updated.bib"
 RESULTS_FILE="results.bib"
-PARALLEL=32
+PARALLEL=16
 
 
 echo "Step 1: Fetching metadata ..."
@@ -32,7 +32,7 @@ echo "$DOCUMENTS" | (
       rm -f ${name}.bib
       if [[ "${name}" =~ ^(RFC[0-9]+$)|(draft-[a-z].*$) ]] ; then
          # echo >&2 "Processing ${name} ..."
-         echo "./ietf2bibtex --quiet \"${name}\" >${name}.bib"
+         echo "./ietf2bibtex \"${name}\" >${name}.bib"
       else
          echo >&2 "Skipping ${name}"
       fi
@@ -46,7 +46,9 @@ echo "$DOCUMENTS" | (
    while read name ; do
       if [ -e ${name}.bib ] ; then
          if [ "`stat --format="%s" ${name}.bib`" != "0" ] ; then
-            echo "./bibtexconv ${name}.bib -export-to-bibtex=${name}.bib2 -check-urls -only-check-new-urls -non-interactive || echo \"ERROR: ${name}.bib seems to be invalid!\""
+# !!!!!!!!!!!!!!!!!!!!!!!! CHECK OFF!
+            echo "./bibtexconv ${name}.bib -export-to-bibtex=${name}.bib2 -only-check-new-urls -non-interactive || echo \"ERROR: ${name}.bib seems to be invalid!\""
+# !!!!            echo "./bibtexconv ${name}.bib -export-to-bibtex=${name}.bib2 -check-urls -only-check-new-urls -non-interactive || echo \"ERROR: ${name}.bib seems to be invalid!\""
          else
             echo >&2 "NOTE: Removing empty file ${name}.bib"
             rm -f ${name}.bib
@@ -74,5 +76,7 @@ echo "Done."
 
 
 echo "Step 4: Showing differences ..."
-diff ~/src/papers/Referenzarchiv.bib ${RESULTS_FILE} | grep -v url.checked | grep -v -E '^[[:alnum:]]+' | grep -v "^---$"
+diff ~/src/papers/Referenzarchiv.bib ${RESULTS_FILE} | grep -v url.checked | grep -v -E '^[[:alnum:]]+' | grep -v "^---$"| grep -v "[ \t]*url[.a-z0-9]* ="
 colordiff ${REFERENCES} ${RESULTS_FILE} |grep author|grep -B1 '>'
+
+exit 1
