Improved script.

diff --git a/src/update-ietf-documents b/src/update-ietf-documents
--- a/src/update-ietf-documents
+++ b/src/update-ietf-documents
@@ -29,35 +29,50 @@ PARALLEL=32
 echo "Step 1: Fetching metadata ..."
 echo "$DOCUMENTS" | (
    while read name ; do
+      rm -f ${name}.bib
       if [[ "${name}" =~ ^(RFC[0-9]+$)|(draft-[a-z].*$) ]] ; then
          # echo >&2 "Processing ${name} ..."
          echo "./ietf2bibtex --quiet \"${name}\" >${name}.bib"
       else
-         echo "Skipping ${name}"
+         echo >&2 "Skipping ${name}"
       fi
    done
 ) | parallel -j${PARALLEL}
+wait
 
 
 echo "Step 2: Fetching documents ..."
 echo "$DOCUMENTS" | (
    while read name ; do
-      echo "./bibtexconv ${name}.bib -export-to-bibtex=${name}.bib2 -check-urls -only-check-new-urls -non-interactive"
+      if [ -e ${name}.bib ] ; then
+         if [ "`stat --format="%s" ${name}.bib`" != "0" ] ; then
+            echo "./bibtexconv ${name}.bib -export-to-bibtex=${name}.bib2 -check-urls -only-check-new-urls -non-interactive || echo \"ERROR: ${name}.bib seems to be invalid!\""
+         else
+            echo >&2 "NOTE: Removing empty file ${name}.bib"
+            rm -f ${name}.bib
+         fi
+      fi
    done
 ) | parallel -j${PARALLEL}
+wait
 
 
 echo "Step 3: Collecting results ..."
-cat ${REFERENCES} >${UPDATES_FILE}
-echo "$DOCUMENTS" | (
-   while read name ; do
-      cat ${name}.bib2 >>${UPDATES_FILE}
-      rm -f ${name}.bib ${name}.bib2
-   done
-)
+(
+   cat ${REFERENCES}
+   echo "$DOCUMENTS" | (
+      while read name ; do
+         if [ -e ${name}.bib2 ] ; then
+            cat ${name}.bib2
+         fi
+         rm -f ${name}.bib ${name}.bib2
+      done
+   )
+)  >${UPDATES_FILE}
 ./bibtexconv ${UPDATES_FILE} -export-to-bibtex=${RESULTS_FILE} -non-interactive
 echo "Done."
 
 
+echo "Step 4: Showing differences ..."
 diff ~/src/papers/Referenzarchiv.bib ${RESULTS_FILE} | grep -v url.checked | grep -v -E '^[[:alnum:]]+' | grep -v "^---$"
 colordiff ${REFERENCES} ${RESULTS_FILE} |grep author|grep -B1 '>'
