Improved script.

diff --git a/src/update-ietf-documents b/src/update-ietf-documents
--- a/src/update-ietf-documents
+++ b/src/update-ietf-documents
@@ -20,12 +20,12 @@
 #
 
 REFERENCES=~/src/papers/Referenzarchiv.bib
-DOCUMENTS=$(grep -E "^@[a-zA-Z]*{[ \t].*,.*$" "${REFERENCES}" | sed -e "s/,//g" | awk '{ print $2; }' | grep -E "^RFC|^draft")
+DOCUMENTS="$(grep -E "^@[a-zA-Z]*{[ \t].*,.*$" "${REFERENCES}" | sed -e "s/,//g" | awk '{ print $2; }' | grep -E "^RFC|^draft")"
 UPDATES_FILE="updated.bib"
 RESULTS_FILE="results.bib"
 PARALLEL=16
 
-BIBTEXCONV_OPTIONS="-check-urls"
+BIBTEXCONV_OPTIONS="--check-urls"
 IETF2BIBTEX_OPTIONS="--quiet"
 
 if [ "$1" == "--test" ] ; then
@@ -34,9 +34,8 @@ if [ "$1" == "--test" ] ; then
    echo "!!! Test Mode !!!"
 fi
 
-
 echo "Step 1: Fetching metadata ..."
-echo "$DOCUMENTS" | (
+echo "${DOCUMENTS}" | (
    while read -r name ; do
       rm -f "${name}".bib
       if [[ "${name}" =~ ^(RFC[0-9]+$)|(draft-[a-z].*$) ]] ; then
@@ -51,11 +50,11 @@ wait
 
 
 echo "Step 2: Fetching documents ..."
-echo "$DOCUMENTS" | (
+echo "${DOCUMENTS}" | (
    while read -r name ; do
       if [ -e "${name}".bib ] ; then
          if [ "$(stat --format="%s" "${name}".bib)" != "0" ] ; then
-            echo "./bibtexconv ${name}.bib -export-to-bibtex=${name}.bib2 ${BIBTEXCONV_OPTIONS} -only-check-new-urls -non-interactive || echo \"ERROR: ${name}.bib seems to be invalid!\""
+            echo "./bibtexconv ${name}.bib --export-to-bibtex ${name}.bib2 ${BIBTEXCONV_OPTIONS} --only-check-new-urls --non-interactive || echo \"ERROR: ${name}.bib seems to be invalid!\""
          else
             echo >&2 "NOTE: Removing empty file ${name}.bib"
             rm -f "${name}".bib
@@ -68,8 +67,8 @@ wait
 
 echo "Step 3: Collecting results ..."
 (
-   cat ${REFERENCES}
-   echo "$DOCUMENTS" | (
+   cat "${REFERENCES}"
+   echo "${DOCUMENTS}" | (
       while read -r name ; do
          if [ -e "${name}".bib2 ] ; then
             cat "${name}".bib2
@@ -77,11 +76,12 @@ echo "Step 3: Collecting results ..."
          rm -f "${name}".bib "${name}".bib2
       done
    )
-)  >${UPDATES_FILE}
-./bibtexconv ${UPDATES_FILE} -export-to-bibtex=${RESULTS_FILE} -non-interactive
+)  >"${UPDATES_FILE}"
+./bibtexconv "${UPDATES_FILE}" --export-to-bibtex "${RESULTS_FILE}" --non-interactive
 echo "Done."
 
 
-echo "Step 4: Showing differences ..."
-diff ~/src/papers/Referenzarchiv.bib ${RESULTS_FILE} | grep -v url.checked | grep -v -E '^[[:alnum:]]+' | grep -v "^---$"| grep -v "[ \t]*url[.a-z0-9]* ="
-diff --color ${REFERENCES} ${RESULTS_FILE} |grep author|grep -B1 '>'
+echo "Step 4: Showing differences (${REFERENCES} ${RESULTS_FILE}) ..."
+ls -l "${REFERENCES}" "${RESULTS_FILE}"
+diff "${REFERENCES}" "${RESULTS_FILE}" | grep -v url.checked | grep -v -E '^[[:alnum:]]+' | grep -v "^---$"| grep -v "[ \t]*url[.a-z0-9]* ="
+diff --color ${REFERENCES} "${RESULTS_FILE}" |grep author|grep -B1 '>'
