Another update.

diff --git a/src/update-ietf-documents b/src/update-ietf-documents
--- a/src/update-ietf-documents
+++ b/src/update-ietf-documents
@@ -25,6 +25,15 @@ UPDATES_FILE="updated.bib"
 RESULTS_FILE="results.bib"
 PARALLEL=16
 
+BIBTEXCONV_OPTIONS="-check-urls"
+IETF2BIBTEX_OPTIONS="--quiet"
+
+if [ "$1" == "--test" ] ; then
+   BIBTEXCONV_OPTIONS=""    # Do no check URLs
+   IETF2BIBTEX_OPTIONS=""   # Verbose mode
+   echo "!!! Test Mode !!!"
+fi
+
 
 echo "Step 1: Fetching metadata ..."
 echo "$DOCUMENTS" | (
@@ -32,7 +41,7 @@ echo "$DOCUMENTS" | (
       rm -f ${name}.bib
       if [[ "${name}" =~ ^(RFC[0-9]+$)|(draft-[a-z].*$) ]] ; then
          # echo >&2 "Processing ${name} ..."
-         echo "./ietf2bibtex \"${name}\" >${name}.bib"
+         echo "./ietf2bibtex ${IETF2BIBTEX_OPTIONS} \"${name}\" >${name}.bib"
       else
          echo >&2 "Skipping ${name}"
       fi
@@ -46,9 +55,7 @@ echo "$DOCUMENTS" | (
    while read name ; do
       if [ -e ${name}.bib ] ; then
          if [ "`stat --format="%s" ${name}.bib`" != "0" ] ; then
-# !!!!!!!!!!!!!!!!!!!!!!!! CHECK OFF!
-            echo "./bibtexconv ${name}.bib -export-to-bibtex=${name}.bib2 -only-check-new-urls -non-interactive || echo \"ERROR: ${name}.bib seems to be invalid!\""
-# !!!!            echo "./bibtexconv ${name}.bib -export-to-bibtex=${name}.bib2 -check-urls -only-check-new-urls -non-interactive || echo \"ERROR: ${name}.bib seems to be invalid!\""
+            echo "./bibtexconv ${name}.bib -export-to-bibtex=${name}.bib2 ${BIBTEXCONV_OPTIONS} -only-check-new-urls -non-interactive || echo \"ERROR: ${name}.bib seems to be invalid!\""
          else
             echo >&2 "NOTE: Removing empty file ${name}.bib"
             rm -f ${name}.bib
@@ -78,5 +85,3 @@ echo "Done."
 echo "Step 4: Showing differences ..."
 diff ~/src/papers/Referenzarchiv.bib ${RESULTS_FILE} | grep -v url.checked | grep -v -E '^[[:alnum:]]+' | grep -v "^---$"| grep -v "[ \t]*url[.a-z0-9]* ="
 colordiff ${REFERENCES} ${RESULTS_FILE} |grep author|grep -B1 '>'
-
-exit 1
